version: "3.5"
volumes:
  php-fpm-socket:
  db-store:
  node-modules:
services:
  mysql:
    env_file:
      - ./.env
    ports:
      - ${MYSQL_PORT:-3307}:3306
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-laravel}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secret}
    networks:
      - app-network-backend

  app:
    build:
      context: ./docker
      dockerfile: ./php/Dockerfile
    env_file:
      - ./.env
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./:/app
    environment:
      - DB_CONNECTION=${DB_CONNECTION:-mysql}
      - DB_HOST=mysql
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-laravel}
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-secret}
    networks:
      - app-network
      - app-network-backend

  web:
    build:
      context: ./docker
      dockerfile: ./nginx/Dockerfile
    env_file:
      - ./.env
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./:/app
    ports:
      - ${WEB_PORT:-8000}:80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  app-network-backend:
    driver: bridge
